# Generated by Django 2.2.4 on 2019-08-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ghin',
            field=models.CharField(blank=True, help_text='GHIN or OTHER', max_length=12),
        ),
    ]
