# Generated by Django 2.2.4 on 2019-10-16 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.PositiveSmallIntegerField(choices=[(1, 'Front'), (2, 'Back')], default=1)),
                ('hole_number', models.PositiveSmallIntegerField(choices=[(1, 'Hole 1'), (2, 'Hole 2'), (3, 'Hole 3'), (4, 'Hole 4'), (5, 'Hole 5'), (6, 'Hole 6'), (7, 'Hole 7'), (8, 'Hole 8'), (9, 'Hole 9'), (10, 'Hole 10'), (11, 'Hole 11'), (12, 'Hole 12'), (13, 'Hole 13'), (14, 'Hole 14'), (15, 'Hole 15'), (16, 'Hole 16'), (17, 'Hole 17'), (18, 'Hole 18')], default=1)),
                ('handicap', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18')], default=1)),
                ('par', models.PositiveSmallIntegerField(choices=[(3, '3'), (4, '4'), (5, '5')], default=4)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tee_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=4)),
                ('slope', models.PositiveSmallIntegerField()),
                ('holecount', models.PositiveSmallIntegerField(choices=[(9, 'Nine Holes'), (18, 'Eighteen Holes')], default=18)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('couse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('holes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Hole')),
            ],
        ),
    ]
